[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "shadthon"
version = "0.2.0"
description = "Modern asynchronous Python 3.14 client for Shad Messenger"
readme = "README.md"
requires-python = ">=3.14"
license = {text = "MIT"}

dependencies = [
    "aiohttp>=3.9.0",
    "pycryptodome>=3.20.0"
]

[project.urls]
Homepage = "https://github.com/HidMart/shadthon"
Repository = "https://github.com/HidMart/shadthon"

[tool.setuptools.packages.find]
include = ["shadthon*"]