[build-system]
requires = [
    "setuptools>=68",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "shadthon"
version = "0.3.0"
description = "Async Python framework for Shad Messenger"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}

dependencies = [
    "aiohttp>=3.9",
    "pycryptodome>=3.20",
    "websockets>=12,<16"
]

[project.urls]
Homepage = "https://github.com/HidMart/shadthon"
Repository = "https://github.com/HidMart/shadthon"

[tool.setuptools.packages.find]
include = ["shadthon*"]